/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class BsDiffUtil */

#ifndef _Included_BsDiffUtil
#define _Included_BsDiffUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     BsDiffUtil
 * Method:    bsDiffFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_BsDiffUtil_bsDiffFile
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
